language: node_js
cache: yarn
after_script:
- npm run codecov
sudo: false
addons:
  ssh_known_hosts: design.optimizely.com
before_deploy:
# Start from scratch
- rm -rfv dist
- npm run build
# Remove `devDependencies` from `package.json` before it goes to npm.
- ./node_modules/.bin/json -I -f package.json -e 'this.devDependencies={}'
# Prepare for deploying React documentation with SSH
# https://oncletom.io/2016/travis-ssh-deploy/
# - eval "$(ssh-agent -s)"
# - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
# - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
- provider: npm
  skip_cleanup: true
  api_key:
    secure: lHK9LAw3CJ+yEpdLLU6qgfWtjm9l8MoWQVsvx9z2uVSUtKguZMgT6oD8Y660h40TxtSnD4B/+2ST/50++k+tAN/2AFAoH5N5dpQdR7wzzF+hmuYkz/zRpL0MXuc+Nj3GpORaq4gSOMT3mH8BCAXFNI7jtBdvGF89N3Ag7u1zsMU=
  email:
    secure: cKTOKErgXo7WcyaqQFzBIGBpEz5X+MwtN/wHXNmLDU6BJ98IKfRcOS2oY8jG/JFoy+EQDdC8iwLfN7+z8gysMoVVbZYm/sKKLg2UXEBCe02p1mJlPDh/o/E+9ofNe1PMv/o1j4CY3YBfaVA+HB7WCGyKivu6tFgFOuoxbPdOleA=
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: scripts/docs-deploy.sh
  on:
    tags: true
# before_install:
# - openssl aes-256-cbc -K $encrypted_310f735a6883_key -iv $encrypted_310f735a6883_iv -in deploy_rsa.enc -out deploy_rsa -d
after_install:
- ssh-agent -k
