language: node_js
install:
- bundle install
- npm install
script:
- npm test
dist: trusty
sudo: false
addons:
  ssh_known_hosts: design.optimizely.com
before_deploy:
# Start from scratch
- rm -rfv dist
- npm start
# Remove `devDependencies` from `package.json` before it goes to npm.
- ./node_modules/.bin/json -I -f package.json -e 'this.devDependencies={}'
# Prepare for deploying React documentation with SSH
# https://oncletom.io/2016/travis-ssh-deploy/
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
- provider: npm
  email:
    secure: Y+A/HOGTYtASn+cHBFxslq52Ij8sdS5I+uvKiZF6466fwJytlGzdyR9e+4NGkul0UgJl3CUY5xKZ7LhyNBPxQUaG9DmlX8pkDiuHlcFlMbCtw+aTLhRS+pfpGbOlKZUWZcM5jZF+TvPIEqN/q5/p5kZnIqp9dmVijOSu7/t0zxA=
  api_key:
    secure: bO19tV7KI0p1L+YoQsaKnfGqYOa+DkvUVq424j88ljYUE2FzH16vtRZgH1FZkWKJ5wZkd20WpPLDkrVe0jU4iQ0KhFGj0avO1iAvAsYPs61ZfZ7HM7pseR5seJ9AvXov7ojoFbUwuyVLDpMOp3QhOJStYoTomvfbkAWjWHiOliM=
  on:
    tags: true
    condition: "$(git describe --tags $(git rev-list --tags --max-count=1)) != *-*"
- provider: script
  script: scripts/docs-deploy.sh
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_310f735a6883_key -iv $encrypted_310f735a6883_iv -in deploy_rsa.enc -out deploy_rsa -d
